#!/bin/sh
#BSUB -q waic-short
#BSUB -oo out.%J
#BSUB -eo err.%J
#BSUB -app nvidia-gpu
#BSUB -env LSB_CONTAINER_IMAGE=nvcr.io/nvidia/pytorch:19.09-py3
#BSUB -gpu num=8:j_exclusive=yes
python3 -m torch.distributed.launch --nproc_per_node=8 --use_env csPose/train_cs.py --data-path /home/labs/waic/shared/coco/ \
-b 4 -e 1 --output-dir resnet18/run1 --num-workers 4 --resume auto --world-size 8 --print-freq 50 --plot-freq 12
